### ISSUE TITLE
Unhandled exception. System.InvalidOperationException: The Style already has a parent.

### ISSUE THREAD

**Issue by maifeeulasad** [waliarubal/Jaya#98]
I tried to run the UI project with **`dotnet run --project Jaya.Ui`**

And I got the following error : 
```
Unhandled exception. System.InvalidOperationException: The Style already has a parent.
   at Avalonia.Styling.Style.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Avalonia.Styling/Styling/Style.cs:line 145
   at Avalonia.Markup.Xaml.Styling.StyleInclude.Avalonia.Controls.IResourceProvider.AddOwner(IResourceHost owner) in /_/src/Markup/Avalonia.Markup.Xaml/Styling/StyleInclude.cs:line 98
   at Avalonia.Styling.Styles.<OnCollectionChanged>g__Add|52_1(IList items) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 292
   at Avalonia.Styling.Styles.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 318
   at Avalonia.Collections.AvaloniaList`1.NotifyAdd(T item, Int32 index) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 683
   at Avalonia.Collections.AvaloniaList`1.Add(T item) in /_/src/Avalonia.Base/Collections/AvaloniaList.cs:line 206
   at Avalonia.Styling.Styles.Add(IStyle item) in /_/src/Avalonia.Styling/Styling/Styles.cs:line 201
   at Jaya.Shared.ThemeManager.set_SelectedTheme(ThemeModel value) in /home/mua/Desktop/Jaya/src/Jaya.Shared/ThemeManager.cs:line 88
   at Jaya.Ui.Models.ApplicationConfigModel.set_Theme(ThemeModel value) in /home/mua/Desktop/Jaya/src/Jaya.Ui/Models/ApplicationConfigModel.cs:line 59
   at Jaya.Ui.Models.ApplicationConfigModel.SetTheme(String name) in /home/mua/Desktop/Jaya/src/Jaya.Ui/Models/ApplicationConfigModel.cs:line 82
   at Jaya.Ui.Models.ApplicationConfigModel.set_ThemeName(String value) in /home/mua/Desktop/Jaya/src/Jaya.Ui/Models/ApplicationConfigModel.cs:line 72
   at Jaya.Ui.Models.ApplicationConfigModel.Empty() in /home/mua/Desktop/Jaya/src/Jaya.Ui/Models/ApplicationConfigModel.cs:line 90
   at Jaya.Shared.Base.ConfigModelBase.Empty[T]() in /home/mua/Desktop/Jaya/src/Jaya.Shared/Base/ConfigModelBase.cs:line 15
   at Jaya.Shared.Services.ConfigurationService.GetOrDefault[T](String key) in /home/mua/Desktop/Jaya/src/Jaya.Shared/Services/Configuration/ConfigurationService.cs:line 51
   at Jaya.Ui.Services.SharedService.LoadConfigurations() in /home/mua/Desktop/Jaya/src/Jaya.Ui/Services/SharedService.cs:line 51
   at Jaya.Ui.App.OnFrameworkInitializationCompleted() in /home/mua/Desktop/Jaya/src/Jaya.Ui/App.xaml.cs:line 28
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 313
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 180
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 134
   at Jaya.Ui.Program.Main(String[] args) in /home/mua/Desktop/Jaya/src/Jaya.Ui/Program.cs:line 26

```

**Comment by waliarubal** [comment]
Rewriting the project, this is no more relevant.
